// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app

import (
	"context"
	"github.com/bruli/pinger/internal/domain"
	"sync"
)

// Ensure, that PingExecutorMock does implement PingExecutor.
// If this is not the case, regenerate this file with moq.
var _ PingExecutor = &PingExecutorMock{}

// PingExecutorMock is a mock implementation of PingExecutor.
//
//	func TestSomethingThatUsesPingExecutor(t *testing.T) {
//
//		// make and configure a mocked PingExecutor
//		mockedPingExecutor := &PingExecutorMock{
//			ExecuteFunc: func(ctx context.Context, p *domain.Ping) (domain.Latency, error) {
//				panic("mock out the Execute method")
//			},
//		}
//
//		// use mockedPingExecutor in code that requires PingExecutor
//		// and then make assertions.
//
//	}
type PingExecutorMock struct {
	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context, p *domain.Ping) (domain.Latency, error)

	// calls tracks calls to the methods.
	calls struct {
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *domain.Ping
		}
	}
	lockExecute sync.RWMutex
}

// Execute calls ExecuteFunc.
func (mock *PingExecutorMock) Execute(ctx context.Context, p *domain.Ping) (domain.Latency, error) {
	if mock.ExecuteFunc == nil {
		panic("PingExecutorMock.ExecuteFunc: method is nil but PingExecutor.Execute was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   *domain.Ping
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(ctx, p)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedPingExecutor.ExecuteCalls())
func (mock *PingExecutorMock) ExecuteCalls() []struct {
	Ctx context.Context
	P   *domain.Ping
} {
	var calls []struct {
		Ctx context.Context
		P   *domain.Ping
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}
