// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package app

import (
	"context"
	"github.com/bruli/pinger/internal/domain"
	"sync"
)

// Ensure, that PingRepositoryMock does implement PingRepository.
// If this is not the case, regenerate this file with moq.
var _ PingRepository = &PingRepositoryMock{}

// PingRepositoryMock is a mock implementation of PingRepository.
//
//	func TestSomethingThatUsesPingRepository(t *testing.T) {
//
//		// make and configure a mocked PingRepository
//		mockedPingRepository := &PingRepositoryMock{
//			FindFunc: func(ctx context.Context) ([]*domain.Ping, error) {
//				panic("mock out the Find method")
//			},
//		}
//
//		// use mockedPingRepository in code that requires PingRepository
//		// and then make assertions.
//
//	}
type PingRepositoryMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context) ([]*domain.Ping, error)

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockFind sync.RWMutex
}

// Find calls FindFunc.
func (mock *PingRepositoryMock) Find(ctx context.Context) ([]*domain.Ping, error) {
	if mock.FindFunc == nil {
		panic("PingRepositoryMock.FindFunc: method is nil but PingRepository.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedPingRepository.FindCalls())
func (mock *PingRepositoryMock) FindCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}
